# yaml-language-server: schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
run:
  timeout: 5m
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - goimports
    - gofumpt
    - revive
    - goconst
    - gocritic
    - bodyclose
    - ineffassign
    - typecheck
    - unconvert
    - whitespace
    - prealloc
    - gocognit
    - gocyclo
    - funlen
    - nolintlint
    - dupl
    - gosec
linters-settings:
  goimports:
    local-prefixes: github.com/diskmanti/kds
  gofumpt:
    extra-rules: true
  gocyclo:
    min-complexity: 15
  funlen:
    lines: 100
    statements: 60
  gocognit:
    min-complexity: 20
  errcheck:
    check-type-assertions: true
    check-blank: true
  dupl:
    threshold: 150
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude_rules:
    - path_prefix: _test.go
      linters:
        - funlen
        - goconst
        - dupl
