# .goreleaser.yml
project_name: kds

before:
  hooks:
    - go mod tidy

builds:
  - id: kds
    main: ./main.go
    binary: kds
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: kds
    builds:
      - kds
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge branch"

release:
  github:
    owner: your-github-diskmanti # <-- IMPORTANT: Change this to your GitHub username!
    name: kds # The name of your repository
  draft: false
  prerelease: auto