# Simplified Continuous Integration (CI) workflow.
# It runs on every push and pull request to the main/master branch.
name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59.1

      - name: Run tests
        run: go test -v -race ./...

      - name: Build
        run: go build -v ./...