# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: CI
on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
      - name: Run tests
        run: go test -v -race ./...
      - name: Build
        run: go build -v ./...
